module_name: "fvc"

# NOTE: Frequencies will be converted to an integer number of ms for a delay

buckets:
    high_frequency:
        frequency_hz: 200
        parameters:
            fvcWheelSpeedFrontLeft_m_per_s:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1
            fvcWheelSpeedFrontRight_m_per_s:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1
            fvcWheelSpeedRearLeft_m_per_s:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1
            fvcWheelSpeedRearRight_m_per_s:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1
            fvcShockPosFrontLeft_mm:
                ADC: ADC1_IN1
                sensor: front_left_shock_pos
                samples_buffered: 1
            fvcShockPosFrontRight_mm:
                ADC: ADC1_IN0
                sensor: front_right_shock_pos
                samples_buffered: 1

    medium_freqeuncy:
        frequency_hz: 100
        parameters:
            fvcPedalPosition1_mm:
                ADC: ADC1_IN3
                sensor: linear_pos_sensor_25
                samples_buffered: 1
            fvcPedalPosition2_mm:
                ADC: ADC1_IN14
                sensor: linear_pos_sensor_25
                samples_buffered: 1
            fvcPedalPosition1_percent:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1
            fvcPedalPosition2_percent:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1
            fvcBrakePressureFront_psi:
                ADC: ADC1_IN11
                sensor: brake_pressure_sensor_rife
                samples_buffered: 1
            fvcSteeringAngle_deg:
                ADC: ADC1_IN2
                sensor: steering_angle_sensor
                samples_buffered: 1
            
            fvcVehicleState_state:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1
            fvcDriveControlTickStart_ms:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1
            fvcDriveControlTickEnd_ms:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1

            # Drive Inputs
            fvcSlipTractionLimit_percent:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1

            # Drive Outputs
            fvcSlip_FL_percent:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1
            fvcSlip_FR_percent:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1
            fvcSlip_RL_percent:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1
            fvcSlip_RR_percent:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1

            fvcSlipStatus_FL_state:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1
            fvcSlipStatus_FR_state:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1
            fvcSlipStatus_RL_state:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1
            fvcSlipStatus_RR_state:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1
            
            fvcTau_FL_Nm:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1
            fvcTau_FR_Nm:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1
            fvcTau_RL_Nm:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1
            fvcTau_RR_Nm:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1
            fvcTauTotalCMD_Nm:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1
            fvcCurrentTotalCMD_Apk:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1

    low_freqeuncy:
        frequency_hz: 5
        parameters:
            fvcBrakeTempFrontLeft_C:
                ADC: ADC1_IN6
                sensor: brake_temp_sensor
                samples_buffered: 1
            fvcBrakeTempFrontRight_C:
                ADC: ADC1_IN7
                sensor: brake_temp_sensor
                samples_buffered: 1
            fvcFrontRideHeight_mm:
                ADC: ADC1_IN15
                sensor: full_raw_voltage_sensor
                samples_buffered: 1
            fvcPedalPosition1RangeFault_state:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1
            fvcPedalPosition2RangeFault_state:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1
            fvcPedalPositionCorrelationFault_state:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1
            fvcBothPedalsPressedFault_state:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1
            fvcDisplayFaultStatus_state:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1
            fvcMcuStatus_state:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1
            fvcSdcStatus3:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1
            fvcSdcStatus4:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1
            fvcDriveSpeedMode_state:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1

            # Forwarded Motor/Inverter Temps
            fvcControllerTemp_FL_C:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1
            fvcControllerTemp_FR_C:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1
            fvcControllerTemp_RL_C:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1
            fvcControllerTemp_RR_C:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1
            fvcMotorTemp_FL_C:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1
            fvcMotorTemp_FR_C:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1
            fvcMotorTemp_RL_C:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1
            fvcMotorTemp_RR_C:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1
            
            # Efuse Fault Data
            fvcEfuse3V3SNSFault_state:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1
            fvcEfuse5VSNSFault1_state:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1
            fvcEfuse5VSNSFault2_state:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1
            fvcEfuse5VSWMFault_state:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1
            fvcEfuse12VSNSFault_state:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1
            fvcEfuse12VDispFault_state:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1
            fvcEfuse12VDispCurrent_A:
                ADC: ADC1_IN8
                sensor: fvc_efuse12V_Disp_current_reading
                samples_buffered: 1
            fvcEfuse12VSNSCurrent_A:
                ADC: ADC_IN9
                sensor: fvc_efuse12V_SNS_current_reading
                samples_buffered: 1
                
            fvcGitBranchName:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1
            fvcGitHash_decimal:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1
            fvcGitHasUncommitedChanges:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1
            fvcGitTotalUncommitedChanges:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1
